"""Remove string length constraint on all cols

Revision ID: 482cf64c0f84
Revises: 90504437353d
Create Date: 2024-04-26 13:04:12.894034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "482cf64c0f84"
down_revision: Union[str, None] = "90504437353d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "title",
        existing_type=sa.String(60),
        type_=sa.String(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "authors",
        existing_type=sa.String(60),
        type_=sa.String(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "language_code",
        existing_type=sa.String(60),
        type_=sa.String(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "publisher",
        existing_type=sa.String(60),
        type_=sa.String(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "title",
        existing_type=sa.String(),
        type_=sa.String(60),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "authors",
        existing_type=sa.String(),
        type_=sa.String(60),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "language_code",
        existing_type=sa.String(),
        type_=sa.String(60),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "books",
        "publisher",
        existing_type=sa.String(),
        type_=sa.String(60),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
