"""Remove unique constraint on book title

Revision ID: a6e3b8d42103
Revises: 482cf64c0f84
Create Date: 2024-04-26 13:14:16.060546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6e3b8d42103"
down_revision: Union[str, None] = "482cf64c0f84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("books_title_key", "books", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("books_title_key", "books", ["title"])
    # ### end Alembic commands ###
