version: '3.7'
services:
    etl:
      build: .
      restart: always
      environment:
        DB_URI: ${DB_URI}
      volumes:
        - ./dataset:/usr/app/src/dataset
      ports:
        - '5000:5000'

